### ISSUE TITLE
Not workin 3.6

### ISSUE THREAD

**Issue by krishnakuq** [roshin8/TriviaPredictor#1]
Bhai work nahi kar raha koi trick batao

**Comment by roshin8** [comment]
What is not working? Please explain properly in English

**Comment by srikantbhoi** [comment]
does it give 95% correct answer??

**Comment by roshin8** [comment]
For now it just searches the question in Google.
No form of analysis is done as of now.


Closing this issue as no answer was given for my question from @krishnakuq
